import uuid
import time
from typing import List, Dict, Any, Optional, Union
from pydantic import BaseModel, Field
from enum import Enum

# -------------------------------------------------------------------------
# SYSTEM ENUMS
# -------------------------------------------------------------------------

class ModalityType(str, Enum):
    TEXT = "text"
    IMAGE = "image"
    AUDIO = "audio"
    GAZE_VECTOR = "gaze_vector"

class SystemMode(str, Enum):
    SYSTEM_1_FAST = "system_1_fast"
    SYSTEM_2_DEEP = "system_2_deep"

# -------------------------------------------------------------------------
# MEMORY QUERY SCHEMAS
# -------------------------------------------------------------------------

class MemoryQueryRequest(BaseModel):
    """
    Specifies how the Cognitive Engine asks the Weaviate database for 
    semantic or episodic context before the LLM generates a response.
    """
    query_text: str = Field(..., description="The natural language or keyword query")
    concept_distance: float = Field(default=0.8, description="Maximum semantic distance threshold for vector search (0.0 to 1.0)")
    recency_weight: float = Field(default=0.5, description="Bias toward newer memories (0.0=semantic match only, 1.0=heavily biased to recent)")
    limit: int = Field(default=5, description="Maximum number of memories to retrieve")
    memory_classes: List[str] = Field(default=["EpisodicMemory", "SemanticMemory"], description="Which Weaviate collections to search")

# -------------------------------------------------------------------------
# TOOL INVOCATION SCHEMAS
# -------------------------------------------------------------------------

class ToolInvocationRequest(BaseModel):
    """
    Standard schema for how the Cognitive Engine requests an action 
    (e.g., GLiNER entity extraction, calendar query, OSINT spider).
    """
    tool_name: str = Field(..., description="The registered name of the tool/action")
    tool_args: Dict[str, Any] = Field(default_factory=dict, description="JSON arguments to pass to the tool")
    invocation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    is_blocking: bool = Field(default=True, description="Whether the Cognitive Engine should wait for the result before continuing")

# -------------------------------------------------------------------------
# COGNITIVE I/O SCHEMAS
# -------------------------------------------------------------------------

class MultimodalPayload(BaseModel):
    modality: ModalityType
    content: Union[str, bytes, Dict[str, Any]] = Field(..., description="The actual text, binary payload, or structured data (e.g., gaze struct)")
    metadata: Dict[str, Any] = Field(default_factory=dict)

class CognitiveInput(BaseModel):
    """
    The strict input schema handling multimodal prompts, system settings,
    and passive telemetry (like gaze vectors) flowing into the MoE Reasoning Engine.
    """
    request_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp_ms: int = Field(default_factory=lambda: int(time.time() * 1000))
    mode: SystemMode = Field(default=SystemMode.SYSTEM_1_FAST)
    
    # Primary Prompt Data
    payloads: List[MultimodalPayload] = Field(..., description="List of multimodal inputs including text prompt, images, or audio")
    
    # Peripheral Context
    gaze_vectors: Optional[Dict[str, float]] = Field(None, description="Passive eye-tracking coordinates for UI context if applicable (e.g. { 'x': 45.2, 'y': 88.0 })")
    
    # Optional explicitly injected pre-retrieved context
    injected_context: Optional[List[Dict[str, Any]]] = Field(None, description="Previously retrieved Weaviate context forced into this prompt")

class CognitiveOutput(BaseModel):
    """
    The strict output schema handling raw LLM text, tool invocation requests,
    and confidence metrics generated by the MoE architecture.
    """
    response_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    request_id: str = Field(..., description="Must map back to the original CognitiveInput.request_id")
    timestamp_ms: int = Field(default_factory=lambda: int(time.time() * 1000))
    
    # The actual output
    raw_text: str = Field(default="", description="The LLM natural language response")
    
    # Tool usage
    tool_invocations: List[ToolInvocationRequest] = Field(default_factory=list, description="Any systems/tools the engine decided it needs to execute")
    
    # Engine Meta
    confidence_score: float = Field(default=1.0, description="The model's confidence in its reply (0.0 to 1.0)")
    routing_path: str = Field(default="system_1_core", description="Which specific MoE node or path handled the execution")
